//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Common.DataTransferObjects
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

    [Serializable()]	
	public class Address
	{
		public virtual string Street 
        { 
            get;
			set;
		}

		public virtual string PostalCode
		{
			get;
			set;
		}

		public virtual string City
		{
			get;
			set;
		}

	}
}

