//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Common.DataTransferObjects
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Analysis
	{
		public virtual string Name
		{
			get;
			set;
		}

		public virtual float ExtremeMaxValue
		{
			get;
			set;
		}

		public virtual string UnitOfMeasure
		{
			get;
			set;
		}

		public virtual float PriceInEuro
		{
			get;
			set;
		}

		public virtual float ExtremeMinValue
		{
			get;
			set;
		}

		public virtual SampleType SampleType
		{
			get;
			set;
		}

	}
}

