//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Common.DataTransferObjects
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.Text;

	public class Analysis
	{
        [Key]
		public virtual string Name
		{
			get;
			set;
		}

		public virtual float ExtremeMaxValue
		{
			get;
			set;
		}

		public virtual string UnitOfMeasure
		{
			get;
			set;
		}

		public virtual float PriceInEuro
		{
			get;
			set;
		}

		public virtual float ExtremeMinValue
		{
			get;
			set;
		}

		public virtual SampleType SampleType
		{
			get;
			set;
		}

	    public Analysis()
	    {
	        
	    }

        public Analysis(String name, float extremeMinValue, float extremeMaxValue, string unitOfMeasure, float price, SampleType type)
        {
            Name = name;
            ExtremeMaxValue = extremeMaxValue;
            ExtremeMinValue = extremeMinValue;
            UnitOfMeasure = unitOfMeasure;
            PriceInEuro = price;
            SampleType = type;
        }

	}
}

