//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Common.DataTransferObjects
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.Text;

	public class BankAccount
	{
		public virtual string AccountOwner
		{
			get;
			set;
		}

        [Key]
		public virtual string IBAN
		{
			get;
			set;
		}

	    public BankAccount()
	    {
	        
	    }

	    public BankAccount(string iban, string accountOwner)
	    {
	        IBAN = iban;
	        AccountOwner = accountOwner;
	    }

	}
}

