//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Common.DataTransferObjects
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.Text;

	public class Car
	{
        [Key]
		public virtual string CarID
		{
			get;
			set;
		}

		public virtual bool Roadworthy
		{
			get;
			set;
		}

		public virtual GPSPosition LastPosition
		{
			get;
			set;
		}

		public virtual Driver CurrentDriver
		{
			get;
			set;
		}

		public virtual CarLogbook CarLogbook
		{
			get;
			set;
		}

	}
}

