//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Common.DataTransferObjects
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;
    using System.Text;

	public class CarLogbookEntry
	{
		public virtual float StartKM
		{
			get;
			set;
		}

		public virtual float? EndKM
		{
			get;
			set;
		}
        
        [Key, Column(Order = 1)]
		public virtual DateTime StartDate
		{
			get;
			set;
		}

		public virtual DateTime? EndDate
		{
			get;
			set;
		}

        [Key, Column(Order = 0)]
		public virtual Driver Driver
		{
			get;
			set;
		}

	}
}

