//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Common.DataTransferObjects
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.Text;

	public class Customer
	{
		public virtual string LastName
		{
			get;
			set;
		}

		public virtual string FirstName
		{
			get;
			set;
		}

		public virtual string Label
		{
			get;
			set;
		}

		public virtual string Title
		{
			get;
			set;
		}

        [Key]
		public virtual string UserName
		{
			get;
			set;
		}

		public virtual string Password
		{
			get;
			set;
		}

		public virtual string MobileNumber
		{
			get;
			set;
		}

		public virtual bool SMSRequested
		{
			get;
			set;
		}

		public virtual float TwoWayRoadCostInEuro
		{
			get;
			set;
		}

		public virtual Address Address
		{
			get;
			set;
		}

		public virtual BankAccount BankAccount
		{
			get;
			set;
		}

	    public Customer()
	    {
	        
	    }

	    public Customer(string firstname, string lastname, string username, string password, Address address, string label, BankAccount acc, bool smsrequested = false, string mobile = null )
	    {
	        FirstName = firstname;
	        LastName = lastname;
	        UserName = username;
	        Password = password;
	        Address = address;
	        Label = label;
	        SMSRequested = smsrequested;
	        MobileNumber = mobile;
	        BankAccount = acc;
	    }

	}
}

