//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Common.DataTransferObjects
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Customer
	{
		public virtual string LastName
		{
			get;
			set;
		}

		public virtual string FirstName
		{
			get;
			set;
		}

		public virtual string Label
		{
			get;
			set;
		}

		public virtual string Title
		{
			get;
			set;
		}

		public virtual string UserName
		{
			get;
			set;
		}

		public virtual string Password
		{
			get;
			set;
		}

		public virtual string MobileNumber
		{
			get;
			set;
		}

		public virtual bool SMSRequested
		{
			get;
			set;
		}

		public virtual float TwoWayRoadCostInEuro
		{
			get;
			set;
		}

		public virtual Address Address
		{
			get;
			set;
		}

		public virtual BankAccount BankAccount
		{
			get;
			set;
		}
	}
}

