//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Common.DataTransferObjects
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class DailyStatistic
	{
		public virtual int NumberOfOrderedOrders
		{
			get;
			set;
		}

		public virtual int NumberOfOrdersInProgress
		{
			get;
			set;
		}

		public virtual int NumberOfNewOrders
		{
			get;
			set;
		}

		public virtual int NumberOfTestsInProgress
		{
			get;
			set;
		}

		public virtual int NumberOfCompletedTests
		{
			get;
			set;
		}

	}
}

