//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Common.DataTransferObjects
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;
    using System.Text;

	public class Employee
	{

        [Key, Column(Order = 0)]
		public virtual string LastName
		{
			get;
			set;
		}

        [Key, Column(Order = 1)]
		public virtual string FirstName
		{
			get;
			set;
		}

        public virtual string UserName
        {
            get;
            set;
        }

        public virtual string Password
        {
            get;
            set;
        }

        public virtual EEmployeeType EmployeeType 
        {
            get; 
            set;
        }

	}

    public enum EEmployeeType
    {
       TypeDriver = 0,
       TypeAdministrationAssistant = 1,
       TypeLabAssistant = 2
    }
}

