//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Common.DataTransferObjects
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;
    using System.Text;

	public class GPSPosition
	{
        [Key]
        public virtual Guid GPSPositionID { get; set; }
	    public virtual float Latitude { get; set; }
	    public virtual float Longitude { get; set; }

	    public GPSPosition()
	    {
	        GPSPositionID = Guid.NewGuid();
	    }

	}
}

