//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Common.DataTransferObjects
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.Text;

	public class Order
	{
        public Order()
        {

        }
        public Order(Dictionary<string, List<Analysis>> Analysises, Customer Customer)
        {
            this.Customer = Customer;
            this.OrderDate = DateTime.Now;
            this.BringDate = null;
            this.CollectDate = null;
            this.CompleteDate = null;
            this.Test = new List<Test>();
            foreach(KeyValuePair<string, List<Analysis>> kVAnalysises in Analysises)
            {
                foreach(Analysis anal in kVAnalysises.Value)
                {
                    this.Test.Add(new Test(kVAnalysises.Key,anal));
                }
                
            }
            
        }
        [Key]
		public virtual long OrderID
		{
			get;
			set;
		}
        public virtual bool Invoiced
        {
            get;
            set;
        }
		public virtual DateTime? OrderDate
		{
			get;
			set;
		}

		public virtual DateTime? CollectDate
		{
			get;
			set;
		}

		public virtual DateTime? BringDate
		{
			get;
			set;
		}

		public virtual DateTime? CompleteDate
		{
			get;
			set;
		}

		public virtual bool RemindAfterFiveHours
		{
			get;
			set;
		}

		public virtual Customer Customer
		{
			get;
			set;
		}

		public virtual Driver Driver
		{
			get;
			set;
		}

		public virtual IList<Test> Test
		{
			get;
			set;
		}

	}
}

