//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Common.DataTransferObjects
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.Text;

	public class Order
	{
        [Key]
		public virtual long OrderID
		{
			get;
			set;
		}

		public virtual DateTime OrderDate
		{
			get;
			set;
		}

		public virtual DateTime CollectDate
		{
			get;
			set;
		}

		public virtual DateTime BringDate
		{
			get;
			set;
		}

		public virtual DateTime CompleteDate
		{
			get;
			set;
		}

		public virtual bool RemindAfterFiveHours
		{
			get;
			set;
		}

		public virtual Customer Customer
		{
			get;
			set;
		}

		public virtual Driver Driver
		{
			get;
			set;
		}

		public virtual IList<Test> Test
		{
			get;
			set;
		}

	}
}

