//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Common.DataTransferObjects
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Linq;
    using System.Text;

	public enum SampleType : int
	{
        [Description("Blut")]
		BLOOD,
        [Description("Urin")]
		URINE,
        [Description("Stuhl")]
		EXCREMENT,
        [Description("Speichel")]
		SALIVA,
        [Description("Sperma")]
		SPERM
	}
}
