//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Common.DataTransferObjects
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.Text;

	public class Test
	{
        public Test(string PatientID, Analysis anal)
        {
            this.PatientID = PatientID;
            this.Analysis = anal;
            this.TestID = Guid.NewGuid();
            this.TestState = TestState.ORDERED;
            this.AlarmState = AlarmState.NO_ALARM;
            this.StartDate = null;
            this.EndDate = null;
        }
        [Key]
		public virtual Guid TestID
		{
			get;
			set;
		}

		public virtual float ResultValue
		{
			get;
			set;
		}

		public virtual bool Critical
		{
			get;
			set;
		}

		public virtual DateTime? StartDate
		{
			get;
			set;
		}

		public virtual DateTime? EndDate
		{
			get;
			set;
		}

		public virtual string PatientID
		{
			get;
			set;
		}

		public virtual Analysis Analysis
		{
			get;
			set;
		}

		public virtual TestState TestState
		{
			get;
			set;
		}

		public virtual AlarmState AlarmState
		{
			get;
			set;
		}

	}
}

