//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;

namespace Common.DataTransferObjects
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public enum TestState : int
	{
        [Description("Bestellt")]
		ORDERED,
        [Description("Abgeholt")]
		WAITING_FOR_DRIVER,
        [Description("In Bearbeitung")]
		IN_PROGRESS,
        [Description("Abgeschlossen")]
		COMPLETED,
	}
}
