//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace ASPServer.Models
{
    public class BillModel
	{
		public virtual DateTime Date
		{
			get;
			set;
		}

		public virtual string PDFPath
		{
			get;
			set;
		}

	}
}

