//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Web.Mvc;

namespace ASPServer.Models
{
    public class OrderModel
	{
		public virtual string NewPatient
		{
			get;
			set;
		}

		public virtual List<SelectListItem> PatientsList
		{
			get;
			set;
		}

		public virtual string SelectedPatient
		{
			get;
			set;
		}

		public virtual List<Patient> PatientsTable
		{
			get;
			set;
		}

		public virtual Patient Patient
		{
			get;
			set;
		}

	}
}

