//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Web.Mvc;
using Common.DataTransferObjects;

namespace ASPServer.Models
{
    public class OrderModel
	{
        /// <summary>
        /// for textbox value, to add new patients to the list
        /// </summary>
		public virtual string NewPatient
		{
			get;
			set;
		}

        /// <summary>
        /// available Patients
        /// </summary>
		public virtual List<SelectListItem> PatientsList
		{
			get;
			set;
		}

        /// <summary>
        /// Selected Patient to add an analysis
        /// </summary>
		public virtual List<string> SelectedPatient
		{
			get;
			set;
		}

        /// <summary>
        /// List of Analysis to select from
        /// </summary>
        public virtual List<SelectListItem> AnalysisList
        {
            get; 
            set;
        } 

        /// <summary>
        /// Selected Analysis to add to the Patient
        /// </summary>
        public virtual List<string> SelectedAnalysis
        {
            get;
            set;
        }

        /// <summary>
        /// contains all Analysis to order
        /// </summary>
		public virtual Dictionary<string, List<Analysis>> OrderedItems
		{
			get;
			set;
		}

        public OrderModel()
        {
            PatientsList = new List<SelectListItem>();
            OrderedItems = new Dictionary<string, List<Analysis>>();
            AnalysisList = new List<SelectListItem>();
        }
	}
}

