//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Common.DataTransferObjects;

namespace ASPServer.Models
{
    public class Patient
	{
		public virtual string Name
		{
			get;
			set;
		}

		public virtual List<string> Analysis
		{
			get;
			set;
		}

		public virtual List<SampleType> Samples
		{
			get;
			set;
		}

	}
}

