//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Common.DataTransferObjects;

namespace ASPServer.Models
{
    public class ResultModel
	{
		public virtual long OrderNo
		{
			get;
			set;
		}

		public virtual string Patient
		{
			get;
			set;
		}

		public virtual TestState Status
		{
			get;
			set;
		}

		public virtual string Analysis
		{
			get;
			set;
		}

		public virtual float ResultValue
		{
			get;
			set;
		}

		public virtual float MinCritValue
		{
			get;
			set;
		}

		public virtual float MaxCritValue
		{
			get;
			set;
		}

		public virtual bool Critical
		{
			get;
			set;
		}

	}
}

