//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace ASPServer.Models
{
    public class UserModel
	{
		public virtual string ID
		{
			get;
			set;
		}

		public virtual string Password
		{
			get;
			set;
		}

	}
}

