//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace Server.DatabaseCommunication
{
	using Common.DataTransferObjects;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;

	public class DatabaseCommunicator : IDatabaseCommunicator
	{

        private LaborContext Context;

        public List<Analysis> GetAllAnalysis(Func<Analysis, bool> lambda)
        {
            throw new NotImplementedException();
        }

        public List<ShiftSchedule> GetShiftSchedules()
        {
            throw new NotImplementedException();
        }

        public List<Order> GetAllOrders(Func<Order, bool> lambda)
        {
            throw new NotImplementedException();
        }

        public Order GetOrder(long orderID)
        {
            throw new NotImplementedException();
        }

        public Test GetTest(Guid testID)
        {
            throw new NotImplementedException();
        }

        public void EndTransaction(TransactionEndOperation operation)
        {
            if(Context == null)
            {
                throw new Exception("no transaction started, when trying to end transaction");
            }
            if(operation == TransactionEndOperation.SAVE)
            {
                try
                {
                    Context.SaveChanges();
                }
                catch (System.Data.Entity.Validation.DbEntityValidationException dbEx)
                {
                    Exception raise = dbEx;
                    foreach (var validationErrors in dbEx.EntityValidationErrors)
                    {
                        foreach (var validationError in validationErrors.ValidationErrors)
                        {
                            string message = string.Format("{0}:{1}",
                                validationErrors.Entry.Entity.ToString(),
                                validationError.ErrorMessage);
                            // raise a new exception nesting
                            // the current instance as InnerException
                            raise = new InvalidOperationException(message, raise);
                        }
                    }
                    throw raise;
                }
            }
            Context = null;
        }

        public void StartTransaction()
        {
            Context = new LaborContext();
        }

        public void CreateCustomer(Customer customer)
        {
            Context.Customer.Add(customer);
        }

        public List<Test> GetAllTests(Func<Test, bool> lambda)
        {
            throw new NotImplementedException();
        }

        public List<Car> GetAllCars(Func<Car, bool> lambda)
        {
            throw new NotImplementedException();
        }

        public List<Customer> GetAllCustomer(Func<Customer, bool> lambda)
        {
            throw new NotImplementedException();
        }

        public Customer GetCustomer(string userName)
        {
            throw new NotImplementedException();
        }

        public Address GetCustomerAddress(string userName)
        {
            throw new NotImplementedException();
        }

        public void CreateOrder(Order order)
        {
            throw new NotImplementedException();
        }

        public List<Bill> GetAllBills(Func<Bill, bool> lambda)
        {
            throw new NotImplementedException();
        }

        public List<DateTime> GetBillDatesOfMonth(DateTime month)
        {
            throw new NotImplementedException();
        }

        public Bill GetBill(DateTime date)
        {
            throw new NotImplementedException();
        }

        public List<Driver> GetAllDriver(Func<Driver, bool> lambda)
        {
            throw new NotImplementedException();
        }

        public Driver GetDriver(string userName)
        {
            throw new NotImplementedException();
        }

        public Car GetCar(string driverUserName)
        {
            throw new NotImplementedException();
        }

        public Car GetCarbyId(string driverUserName)
        {
            throw new NotImplementedException();
        }

        public CarLogbookEntry GetLastCarLogbookEntry(string carID)
        {
            throw new NotImplementedException();
        }

        public void CreateCarLogbookEnry(CarLogbookEntry entry)
        {
            throw new NotImplementedException();
        }
    }
}

